version: "3.4"
services:
  web:
    build: .
    command: 'sh -c "bundle exec rails db:prepare && bundle exec rails server -p 3000 -b 0.0.0.0"'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - bundler_gems:/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
    depends_on:
      - "db"
    tty: true
    stdin_open: true
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - CLOUDAMQP_URL=amqp://rabbitmq:5672
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - SMTP_HOST=mailcatcher
      - MAILER_SENDER=development@tourrise.de
  webpacker:
    build: .
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/usr/src/app
      - bundler_gems:/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
    ports:
      - 3035:3035
  db:
    image: mariadb:10.4.8
    command:  --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    volumes:
      - bunny_data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    ports:
      - 5672:5672
      - 15672:15672
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

volumes:
  db_data:
  bunny_data:
  bundler_gems:
  node_modules:
  rails_cache:
