# Put this in the file: .github/workflows/verify.yml

name: Update airports on schedule

on:
  push:
    branches:
      - develop
  schedule:
    - cron:  '0 0 * * 0'

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Rake task to update airports
        run: |
          bundle exec rake airports:update

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: airports_update
          commit-message: Update airports
          delete-branch: true
          title: 'Update airports'
          body: |
            Auto-generated airports update.
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
